pipeline {
  agent any
  tools { maven 'Maven3' }
  stages {
    stage('Build') {
      steps {
        dir('backend') {
          sh 'mvn -B -DskipTests clean package'
        }
      }
    }
    stage('Docker Build') {
      steps {
        dir('backend') {
          script {
            def img = "book-website-backend:${env.BUILD_NUMBER}"
            sh "docker build -t ${img} ."
          }
        }
      }
    }
  }
}
